### ISSUE TITLE
HMAC-SHA256 

### ISSUE THREAD

**Issue by starjun** [openresty/lua-resty-string#32]
HMAC-SHA256 是否考虑增加

**Comment by agentzh** [comment]
@starjun Better be in another lua-resty-* library since lua-resty-string is already a mess with too many different things :)

BTW, please do not use Chinese here. This place is considered English only. If you really want to use Chinese, please join the openresty (Chinese) mailing list instead. Please see https://openresty.org/#Community Thanks for your cooperation.

**Comment by hnakamur** [comment]
Hi, I would also like to use HMAC-SHA256 and just found
[jkeys089/lua-resty-hmac: HMAC functions for ngx_lua and LuaJIT](https://github.com/jkeys089/lua-resty-hmac).
I hope this comment is useful for someone who searched on HMAC-SHA256 and OpenResty and find this issue.
